### ISSUE TITLE
pipeline_ingest.concat_filtered_mudatas requires pytz

### ISSUE THREAD

**Issue by wlason** [DendrouLab/panpipes#116]
pipeline_ingest.concat_filtered_mudatas part of the pipeline throws an error because of missing pytz. 

ERROR main control -  \
                                                 \
                                                 \
                                                 \
                                            Original exception: \
                                             \
                                                Exception #1 \
                                                  'builtins.OSError(Job 29542491 has non-zero exitStatus 1: hasExited=True,  wasAborted=FalsehasSignal=False, terminatedSignal=''  \
                                                Traceback (most recent call last): \
                                                  File "[path]/envs/panpipes/lib/python3.9/site-packages/panpipes/python_scripts/concat_adata.py", line 1, in <module> \
                                                    import scanpy as sc \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/scanpy/__init__.py", line 6, in <module> \
                                                    from ._utils import check_versions \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/scanpy/_utils/__init__.py", line 21, in <module> \
                                                    from anndata import AnnData, __version__ as anndata_version \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/anndata/__init__.py", line 7, in <module> \
                                                    from ._core.anndata import AnnData \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/anndata/_core/anndata.py", line 21, in <module> \
                                                    import pandas as pd \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/pandas/__init__.py", line 16, in <module> \
                                                    raise ImportError( \
                                                ImportError: Unable to import required dependencies: \
                                                pytz: No module named 'pytz' \
                                                )' raised in ... \
                                                   Task = def pipeline_ingest.concat_filtered_mudatas(...): \
                                                Traceback (most recent call last): \
                                                  File "[path]/envs/panpipes/lib/python3.9/site-packages/ruffus/task.py", line 712, in run_pooled_job_without_exceptions \
                                                    return_value = job_wrapper(params, user_defined_work_func, \
                                                  File "[path]/envs/panpipes/lib/python3.9/site-packages/ruffus/task.py", line 545, in job_wrapper_io_files \
                                                    ret_val = user_defined_work_func(*params) \
                                                  File "[path]/envs/panpipes/lib/python3.9/site-packages/panpipes/panpipes/pipeline_ingest.py", line 178, in concat_filtered_mudatas \
                                                    P.run(cmd, **job_kwargs) \
                                                  File "[path]/envs/panpipes/lib/python3.9/site-packages/cgatcore/pipeline/execution.py", line 1244, in run \
                                                    benchmark_data = r.run(statement_list) \
                                                  File "[path]/envs/panpipes/lib/python3.9/site-packages/cgatcore/pipeline/execution.py", line 820, in run \
                                                    stdout, stderr, resource_usage = self.queue_manager.collect_single_job_from_cluster( \
                                                  File "[path]/envs/panpipes/lib/python3.9/site-packages/cgatcore/pipeline/cluster.py", line 145, in collect_single_job_from_cluster \
                                                    raise OSError(error_msg) \
                                                OSError: Job 29542491 has non-zero exitStatus 1: hasExited=True,  wasAborted=FalsehasSignal=False, terminatedSignal=''  \
                                                Traceback (most recent call last): \
                                                  File "[path]/envs/panpipes/lib/python3.9/site-packages/panpipes/python_scripts/concat_adata.py", line 1, in <module> \
                                                    import scanpy as sc \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/scanpy/__init__.py", line 6, in <module> \
                                                    from ._utils import check_versions \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/scanpy/_utils/__init__.py", line 21, in <module> \
                                                    from anndata import AnnData, __version__ as anndata_version \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/anndata/__init__.py", line 7, in <module> \
                                                    from ._core.anndata import AnnData \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/anndata/_core/anndata.py", line 21, in <module> \
                                                    import pandas as pd \
                                                  File "[path]/envs/panpipes2/lib/python3.9/site-packages/pandas/__init__.py", line 16, in <module> \
                                                    raise ImportError( \
                                                ImportError: Unable to import required dependencies: \
                                                pytz: No module named 'pytz' \
                                                 \
                                                 \

I removed lines of the log containing individual .h5mu files to protect patient information and replaced my cluster paths with `[path]`. After `conda install -c anaconda pytz` the error persists.

**Comment by crichgriffin** [comment]
Thanks, which of the methods did yu use to install pip or conda?

**Comment by wlason** [comment]
Thanks for the awesome tool! I used conda installation.

**Comment by bio-la** [comment]
hey @wlason i couldn't reproduce this issue, do you still have this issue on your conda env?
