### ISSUE TITLE
MultiVI issue with PyTorch

### ISSUE THREAD

**Issue by wlason** [DendrouLab/panpipes#306]
The multiVi fails at the `mvi.train` in `batch_correct_multivi.py`.

```
Traceback (most recent call last):
  File "[path]/panpipes/panpipes/python_scripts/batch_correct_multivi.py", line 256, in <module>
    mvi.train( **multivi_training_args, **multivi_training_plan)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/model/_multivi.py", line 351, in train
    return runner()
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/train/_trainrunner.py", line 98, in __call__
    self.trainer.fit(self.training_plan, self.data_splitter)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/train/_trainer.py", line 219, in fit
    super().fit(*args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 989, in _run
    results = self._run_stage()
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1035, in _run_stage
    self.fit_loop.run()
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 202, in run
    self.advance()
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 242, in advance
    batch_output = self.manual_optimization.run(kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/manual.py", line 92, in run
    self.advance(kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/manual.py", line 112, in advance
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 382, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/train/_trainingplans.py", line 567, in training_step
    inference_outputs, _, scvi_loss = self.forward(batch, loss_kwargs=self.loss_kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/train/_trainingplans.py", line 278, in forward
    return self.module(*args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/module/base/_base_module.py", line 203, in forward
    return _generic_forward(
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/module/base/_base_module.py", line 739, in _generic_forward
    inference_outputs = module.inference(**inference_inputs, **inference_kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/module/_multivae.py", line 600, in inference
    qzm_acc, qzv_acc, z_acc = self.z_encoder_accessibility(
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/scvi/nn/_base_components.py", line 282, in forward
    dist = Normal(q_m, q_v.sqrt())
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "[path]/panpipes_gpu/lib/python3.10/site-packages/torch/distributions/distribution.py", line 68, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (128, 12)) of distribution Normal(loc: torch.Size([128, 12]), scale: torch.Size([128, 12])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
```

Similar to this issue in scArches: https://github.com/theislab/scarches/issues/206

**Comment by bio-la** [comment]
Hi Wojiciech, thanks for reporting this issue. 
I thought the tensor issue was solved in the latest scvi version (see this [PR](https://github.com/DendrouLab/panpipes/pull/291)) and https://github.com/scverse/scvi-tools/issues/2581
but it seems a slightly different version of the same error. 
can you post the packages versions? thanks!
